### ISSUE TITLE
@stylistic/eslint-plugin와 비슷한 방식으로 구현하기

### ISSUE THREAD

**Issue by Hansanghyeon** [Hansanghyeon/eslint-config#18]
https://eslint.style/

**Comment by Hansanghyeon** [comment]
```
// eslint.config.js
import stylisticTs from '@stylistic/eslint-plugin-ts'
import parserTs from '@typescript-eslint/parser'

export default [
  {
    plugins: {
      '@stylistic/ts': stylisticTs
    },
    parser: parserTs,
    rules: {

      '@stylistic/ts/indent': ['error', 2],
      // ...
    }
  }
]
```

```
    parser: parserTs,
```

해당부분 오류

```[Error - 오전 1:20:44] Calculating config file for file:///root/tools/eslint-config/test/src/test.ts) failed.
ConfigError: Config (unnamed): Key "parser": This appears to be in eslintrc format rather than flat config format.
    at rethrowConfigError (/root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:302:8)
    at /root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:1097:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:1090:43)
    at FlatConfigArray.getConfig (/root/tools/eslint-config/test/node_modules/@eslint/config-array/dist/cjs/index.cjs:1119:15)
    at ESLint.calculateConfigForFile (/root/tools/eslint-config/test/node_modules/eslint/lib/eslint/eslint.js:1173:24)
    at async ESLint.isPathIgnored (/root/tools/eslint-config/test/node_modules/eslint/lib/eslint/eslint.js:1195:24)
    at async /root/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:24295
    at async Object.M [as withClass] (/root/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:19807)
    at async O.then.m.validate (/root/.vscode-server/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:24255)
```

**Comment by Hansanghyeon** [comment]
```
languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: typescriptParser,
    },
```

파서를 이렇게 지정하니까 잘됩니다

<img width="760" alt="image" src="https://github.com/user-attachments/assets/d6052168-f7d3-4bca-acba-9a508c6e3987">
